### ISSUE TITLE
Problem with clean install

### ISSUE THREAD

**Issue by bhaibeka** [waldronlab/PublicDataResources#1]
Hi,

I did a clean install with R 3.6 and got this ewrror:

Error: (converted from warning) packages ‘AnnotationDbi’, ‘curatedMetagenomicData’, ‘curatedTCGAData’, ‘GenomicDataCommons’, ‘GEOquery’, ‘hgu133a.db’, ‘HMP16SData’, ‘phyloseq’, ‘recount’, ‘TCGAbiolinks’ are not available (for R version 3.6.0)

**Comment by LiNk-NY** [comment]
Can you paste the code that you're using? 
These dependencies are listed in the DESCRIPTION file. 
Perhaps you could try: 

```
BiocManager::install("waldronlab/PublicDataResources", dependencies = TRUE, ask = FALSE)
```

**Comment by bhaibeka** [comment]
I was using devtools::nstall_github("waldronlab/PublicDataResources")

BiocManager worked, thanks
