### ISSUE TITLE
Unable to register for workshop

### ISSUE THREAD

**Issue by Rohit-Satyam** [waldronlab/PublicDataResources#7]
I am sorry I have to comment over here but I have been really struggling in the registration of the workshop and today is the last date. I raised my query here but idk why the moderation hasn't completed yet. It's been two days. I can't afford to lose this opportunity. Please please help. I am Rohit Satyam and I raised my concern over here: https://datasciences.eventsmart.com/events/bioc2020/#comment-21

**Comment by LiNk-NY** [comment]
This looks like it has been resolved. Closing. Otherwise, reopen. Thank you!
